destinygg/chat-gui

- assets/chat/js/chat.js
this happened to me and I ended up unsubscribing/resubscribing to remove the mute, because I was stupid and didn't know it was temporary. I later saw the startup hint that mutes are _always_ temporary and felt really stupid about it.
> let muted users know they are not permanently muted 

- assets/chat/js/chat.js
The `/ipban` command issues a permanent, non-IP ban instead of an IP ban. This PR modifies `cmdBAN()` to set `banip` in the ban payload to `true` when the command is used. The chat backend [uses this property](https://github.com/destinygg/chat/blob/5182d05ec93eef658226eea98b87f131644b389a/connection.go#L62) to determine if a ban should be an IP ban.
> Fix `/ipban` command

- assets/chat/js/chat.js
- package.json
This PR modifies `Chat` to accept a ban appeal URL as an argument. If supplied, a "ban appeal hint" will be displayed in chat to users who attempt to connect while banned.
> Update `Chat` to display ban appeal hint

- assets/chat/js/chat.js
- assets/chat/js/mutedtimer.js
- assets/chat/js/source.js
- package-lock.json
- package.json
Being muted in chat is a miserable experience. Not only because you can't post wonderful memes for all your chat friends to appreciate, but also because there's zero feedback as to when your mute expires. Without a clock, just a few minutes can feel like hours.
This PR shows the time left until a mute expires as placeholder text in the chat box. When the mute expires, the original placeholder text is restored. Additionally, chat error messages now display the mute time left, too.
Note that the changes made to destinygg/chat in [this PR](https://github.com/destinygg/chat/pull/36) are necessary for this feature to work. After chat is deployed and website dependencies are updated, send a broadcast message with the text `reload` to force connected users to refresh the page and download the …
> Show users the time left until a mute expires

- assets/chat/js/chat.js
- assets/chat/js/mutedtimer.js
- package-lock.json
- package.json
* Fixes an unfortunate bug related to setting the muted timer that broke stuff a lot. 😫
* Displays the standard placeholder text in DM conversation windows.
* If there's less than one minute left until a mute expires, shows exactly how many seconds to go instead of just `a few seconds`.
> Various fixes for mute duration timer

- assets/chat/js/chat.js
- assets/chat/js/messages.js
- package-lock.json
- package.json
This PR modifies `ChatMessage` to allow for the creation of messages that contain HTML. The class' constructor now accepts an additional parameter, `unformatted`, that dictates whether or not it should run its formatters on the message text. One of the formatters [sanitizes HTML](https://github.com/destinygg/chat-gui/blob/c9381fe51a1b12558f8b44d58e5b4ffd30dbbb45/assets/chat/js/formatters.js#L9-L16) and another [linkifies text](https://github.com/destinygg/chat-gui/blob/c9381fe51a1b12558f8b44d58e5b4ffd30dbbb45/assets/chat/js/formatters.js#L54-L129). With these two formatters disabled, we can easily craft `ChatMessage`s with cleaner-looking links.
Before
After
> Allow disabling formatters when creating a `ChatMessage`

- assets/chat/js/chat.js
- assets/chat/js/formatters.js
- package.json
Hello there!
I noticed that in dgg there's no easy way to:
1. Embed something without posting it in chat (you have to first modify the link, then paste it into the address bar)
2. Post an embed in chat that you don't have embedded currently (once again, you need to modify the link first)
3. Post an embed in chat that you DO have embedded currently (you have to copy it from the address bar)
So I thought I would implement a couple of commands that help with that!
https://user-images.githubusercontent.com/41237021/130905983-d0da4d9e-ffa5-4a7f-85cd-b9956dc03d3c.mp4
Simple enough: ```/embed <link>``` embeds something in bigscreen
https://user-images.githubusercontent.com/41237021/130906124-0ac0a1b5-633b-44b7-b09d-b71325c16fea.mp4
Posts an embed in chat that you either have embedded right now, …
> Some tweaks to improve embed handling

- assets/chat/js/chat.js
Hi there again!
Some time ago I (and some chatters) noticed a bug that allowed you to put as many spaces in a message as you wanted, which could mess up tagging people and/or emotes. Not cool! However, only a limited amount of people experienced it and nobody could quite put a finger on what's causing it.
I thought it was some autocomplete issue messing up messages, turns out it's way more obvious: it's emote regex stuff.
When Steve got unpartnered, all Twitch sub only emotes got turned into normal ones and Twitch subs got removed; recently though, Destiny got affiliate and Twitch subs came back. This caused a regex meme to pop up: for Twitch subs the regex is different, and, with no Twitch sub only emotes, it starts counting spaces as blank emotes.
Here are some screenshots from regex101 …
> Fix twitch subs' ability to spam spaces

- assets/chat/js/autocomplete.js
- assets/chat/js/formatters.js
"spoilers" (with an 's' at the end) used to not highlight links red... Now it does! Very nice! (mentioned in #26)
This is a more of a preliminary bugfix for a bigger autocomplete helper issue: sometimes it goes off the rails and slides off of the screen (if the chat area is small enough, so, like, on a phone). While what I added in (resetting the css of the helper on it's close/timeout) doesn't fix that problem, at least it makes it bearable to chat on mobile without having to refresh once it disappears.
> Assorted bugfixes: autocomplete helper css and spoiler highlighting

- assets/chat/js/chat.js
Just had to add back the ```return``` that got removed with the lint commit (https://github.com/destinygg/chat-gui/commit/594f1290cdff1318845fab073486334566454d46) :smiley:
> fix: history loading after chat connect

- assets/chat/js/chat.js
The last emote listed by /emotes was not being displayed as text: 
/baninfo now shows up on tab completion and is listed on the command list:
Clearer instructions for command hints (such as the ones on /help) and typo fixes.
> Fix /emotes and /baninfo, improve command hints

- assets/chat/js/chat.js
- assets/chat/js/menus/ChatUserInfoMenu.js
- assets/chat/js/user.js
- assets/views/embed.html
As it says in the title, shows the account creation date like this:
Needs https://github.com/destinygg/chat-private/pull/3 merged to function.
> Show account creation date in user info menu

- assets/chat/js/chat.js
The dgg chat on mobile is very annoying to use because every time you press anywhere on the screen it re-focuses the chat input, causing the virtual keyboard to pop up.
See: 
https://user-images.githubusercontent.com/6654122/151734639-38e654dd-4b36-4096-9f1e-2b83d8dc063e.mp4
Obviously you can't see me tap the screen, but I'm doing it every time the mobile keyboard closes and re-opens. It happens if I tap anywhere in the chat, or focus someone's username.
I updated the `focusIfNothingSelected` function to only focus the chat input if the screen-size is greater than 768px.
See:
https://user-images.githubusercontent.com/6654122/151734877-50e0b9ce-b4c5-491d-b835-b913b25912ea.mp4
Tapping in the chat or on a username doesn't focus the input and doesn't bring up the virtual keyboard. At the end …
> Fix mobile keyboard popping up every press

- assets/chat/css/style.scss
- assets/chat/js/menus/ChatUserMenu.js
Not really sure about this one, I just wrapped everything in a div so that the background on hover stops interfering with the gradient.
Ideally there's some simple CSS fix you can do instead, but I couldn't find it :disappointed: 
I don't think this breaks anything, but definitely needs a lil bit more testing :smile: @Mitchdev @11k
> fix: t5 names hiding on hover in user list (#84)

- .github/workflows/bump-and-release.yml
There are [some](https://github.com/npm/cli/issues/1637#issuecomment-802178240) [reports](https://github.com/tabhero/svelte-components/issues/1) that explicitly defining this option fixes the issue.
> Fix error when attempting to publish package to registry in workflow

- assets/chat/js/chat.js
Previously included the @ when matched so when it looked for the name it couldn't find it. (@name != name).
https://github.com/destinygg/chat-gui/blob/master/assets/chat/js/chat.js#L974
@11k
> Fixed nick message regex

- assets/chat/css/style.scss
- assets/chat/js/chat.js
- assets/chat/js/menus/ChatMenu.js
- assets/chat/js/messages/ChatEmoteMessage.js
- assets/chat/js/messages/ChatUIMessage.js
- assets/chat/js/scroll.js
- assets/chat/js/window.js
- assets/views/embed.html
- package-lock.json
- package.json
Swaps out the ancient unmaintained nanoscroller plugin with the shiny new OverlayScrollbars plugin :smile: Based on my, admittedly, unscientific test (spamming chat with 4x1000 generated MSG events to make it lag), this improves performance a decent amount (time decrease of 22.12%):
<details>
<summary>Performance comparison 1</summary>
- nanoscroller:
- OverlayScrollbars:
</details>
Visually, I made it look and behave similarly to the old scrollbar (just a gray rectangle that auto-hides on PC and is always shown on mobile):
<details>
<summary>Scrollbar look</summary>
- nanoscroller:
- OverlayScrollbars:
</details>
In addition to that, by swapping out some jQuery DOM manipulation stuff with native DOM manip stuff, we get another performance boost (17.55% faster compared to the only …
> Replace nanoscroller with OverlayScrollbars/some other scrolling performance improvements

- assets/chat/js/chat.js
On android mobile screens, if you focus an input it brings up the virtual keyboard, which constitutes a `resize` event.
This causes weird bugs with the menus, for instance bringing up the users menu automatically focuses its user-search field, bringing up the virtual keyboard, causing a `resize` event which immediately closes the menu you just opened.
On the chrome app on android, this actually crashes the page.
I can't test this, but I think ios keyboard overlaps and doesn't cause a `resize` event. So this might only be a bug for android phones.
1. Open DGG on a mobile version (one with an actual virtual keyboard, not just the chrome devtools version)
2. Open the emotes or users menu
4. The keyboard causes the menu to close, not allowing you to type anything
I added a check to avoid the …
> Add check to avoid closing menus on resizing on mobile screens

- assets/chat/js/chat.js
Small change, think it would be nice to show aliases, had people ask me why /pe (alias for /postembed) wasn't in /help :smiley: 
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Show aliases in /help

- assets/chat/css/style.scss
so that it doesnt overlap the menus
> fix: decrease the z-index of pinned messages

- assets/chat/js/menus/ChatUserInfoMenu.js
- assets/views/embed.html
Shows a tagged user's tag note in the user info menu. Only ways to currently see a user's tag note is hovering over their name (which can't be done on mobile browsers) or using the tag command and trying to find their username (which can be annoying if a lot of users have been tagged). If the user doesn't have a tag note (either not tagged at all or just tagged with a color), the line is just hidden.
> Add user's tag note to user info menu.

- .github/dependabot.yml
Noticed some dependencies in the `package.json` were out of date. Dependabot can easily assist with this by sending automated PRs; I set it to a weekly interval to make things easier to maintain (daily can be quite annoying sometimes)
Figured this was better than sending the PRs for updating them myself.
> Baseline Dependabot

- assets/chat/js/chat.js
For live streams, Youtube gives a different URL format when getting a URL from the Share button:
https://www.youtube.com/live/XXXXXXXXX?feature=share
Versus the actual URL for stream:
https://www.youtube.com/watch?v=XXXXXXXXX
This causes the /embed and /postembed commands to output the following embed: #youtube/null
This fix checks for the `/live` part, and if so, grab the correct match part containing the video ID.
> Fix embed for YT live share link

- assets/chat/js/chat.js
- assets/chat/js/hashlinkconverter.js
- assets/chat/js/hashlinkconverter.test.js
Added a HashLinkConverter class to handle converting URLs to an embed hash link.
Refactored `/embed` and `/postembed` commands to use this class. (#149)
> Hash link converter and `/embed` and `/postembed` refactor

- assets/chat/js/chat.js
Currently, the `/timestamp` can severely mess up a chatter's account settings and break chat for them. Using `/timestampformat HH mm` for example, removes 'HH' due to slicing the first word off and sets an array of  ['mm'] and breaks chat for them (haven't checked for the exact cause) and no longer see new messages (but can still send), and reloading chat shows nothing nor lets you send any messages afaik.
> Fix `/timestampformat` command

- assets/chat/css/style.scss
<details>
<summary>Current look</summary>
| Firefox  | Chrome |
| ------------- | ------------- |
| ![ksnip_20230224-183608](https://user-images.githubusercontent.com/41237021/221220715-6d3e3163-bd01-4549-8c57-edcb2148ed08.png) | ![ksnip_20230224-183621](https://user-images.githubusercontent.com/41237021/221220792-7d42b744-ad21-4f0b-b831-d2821009cd01.png) |
</details>
<details>
<summary>Old look</summary>
| Firefox  | Chrome |
| ------------- | ------------- |
| ![ksnip_20230224-183711](https://user-images.githubusercontent.com/41237021/221220835-a259827a-2237-4e5c-8823-2a81cabcc4f9.png)  | ![ksnip_20230224-183718](https://user-images.githubusercontent.com/41237021/221220904-bce9e718-4398-47a1-88e7-3fc1e2ac53e7.png)  |
</details>
<details>
<summary>With this change applied</summary>
| …
> Fix on-stream chat text shadows

- assets/chat/js/chat.js
- assets/chat/js/messages/PinnedMessage.js
- assets/chat/js/poll.js
- assets/chat/js/scroll.js
- assets/chat/js/window.js
The "lock" system that's used right now was used to avoid excessive nanoscroller updates by limiting the amount of calls, but since OverlayScrollbars updates the scrollbar automatically it's not really needed.
Making this a draft PR since:
1. I might be overthinking this and there's a way easier solution
2. This needs more testing, since it can cause regressions (I did test a bit and ran into Chrome losing scroll position if you resize the window _too_ much)
For some reason Firefox:
1. Resizes the page/window slightly when you open the new tab
2. Refuses to stick to the bottom of chat on resizes (perhaps the 'resize' event fires too late to catch the right scroll position?)
Those 2 reasons might be the reason it loses the scroll position sometimes.
Closes #171.
> Fix Firefox losing scroll position

- assets/chat/js/formatters/UrlFormatter.js
Continuing the work started in https://github.com/destinygg/chat-gui/pull/117 shortens links over 90 characters to 80 characters with an elipsis.
resolves #113
> Automatically shorten long links

- assets/chat/js/chat.js
Uses moment's .local() method to convert the timestamp in baninfo to a local timestamp
resolves #19
> Convert timestamp to local timezone in ban info

- assets/chat/css/style.scss
If the issue #195 is unintended this will keep pinned messages opaque when chatters are focused.
resolves #195
> Keep pinned messages opaque during focus

- assets/chat/js/chat.js
On chat reconnect, if the pin existed already it would dismiss it automatically, even if it didn't change. Now, if the pin already exists and the UUID matches, we just ignore the event.
> fix: pins auto-dismissing on chat reconnect

- assets/chat/js/chat.js
- assets/chat/js/commands.js
- assets/chat/js/commands.test.js
Closes #179.
Sorts /help alphabetically, also separates admin commands from regular ones. Admin commands only show up if you have mod powers.
| Regular user | Admin |
| ------ | ------ |
| ![ksnip_20230308-183916](https://user-images.githubusercontent.com/41237021/223761637-8a43a93d-869a-4536-9a2c-0554449be858.png) | ![image](https://user-images.githubusercontent.com/41237021/223762249-742b48da-7c79-46f2-be13-39817fec61de.png) |
> Sort /help

- assets/chat/js/autocomplete.js
Resolves mid sentence autocomplete by trimming whitespace from the pre and post string slices in the input event handler, and then depending on any trailing whitespace we determine whether we are mid sentence and slightly reformat the search string. 
might not be the most elegant solution so open to plenty of feedback 😄 
resolves #210
> fix mid sentence autocomplete

- assets/chat/js/chat.js
Revert changes in #261, which resulted in a bug that prevented chat from loading for unregistered users.
> Restore original load settings behavior

- assets/chat/js/chat.js
- assets/chat/js/const.js
- assets/chat/js/regex.js
Builds on the PR #211 and addresses the comments from @11k 
Moves tagcolors, errorstrings, hintstrings and settingsdefault maps into const.js
Refactors errorstrings, hintstrings and settingsdefault into objects.
Moves regexslashcmd, regextime, nickmessageregex, nickregex, nsfwregex, nsflregex into regex.js
Removes nsfwnsflregex
Minor logic adjustments to do with the refactors
resolves #247
> Refactor const usage in chat.js

- assets/chat/js/window.js
Popping the last message from the array can cause problems if messages are received in rapid succession.
> Filter out last message rather than popping

- assets/chat/js/window.js
This fixes a bug where new messages could not be censored because they were cleaned up prematurely.
> Clean up messages from beginning rather than end

- assets/chat/js/const.js
Due to a change in chat's authentication system, users who aren't allowed to chat can now authenticate. Their chat messages are now blocked via the chat backend.
> Add new error for users not allowed to chat

- assets/chat/js/formatters/EmbedUrlFormatter.js
The broken regex was copied directly from `BigscreenManager` in website-private. It's used to identify if a URL's fragment is a valid embed hash link. The regex in `EmbedUrlFormatter` needs to identify hash links among other text in a chat message, so it's slightly different.
> Fix hash link parsing regex

- assets/chat/js/formatters/UrlFormatter.js
- assets/chat/js/hashlinkconverter.js
- assets/chat/js/hashlinkconverter.test.js
This adds timestamp support in the hash link converter so that we can embed youtube links with the right timestamp.
> Add timestamp support to youtube embeds

- assets/chat/js/chat.js
Now looking through tagcolors with a lowercase value, instead of whatever the user is typing.
#305
> Update chat.js cmdTAG - Issue #305

- assets/chat/js/history.js
Apparently the message history (that is, your message history, the up/down arrow one) limit either never worked, or got broken at some point. I'd say this probably isn't an issue for most people, but some REALLY active chatters can chat SO MUCH that they fill up their entire local storage (since it has a 5 or 10 MB limit), which causes the embed bar to break and messages to not disappear from the input on 'send'.
> fix: message history limit not applying

- assets/chat/js/chat.js
Before:
After:
I also restructured the `onMSG` function a lil bit as well so it's clearer what's going on.
> Only combo user messages

- assets/chat/js/formatters/UrlFormatter.js
- assets/chat/js/formatters/UrlFormatter.test.js
Someone suggested it in chat this morning and I thought it was a cute idea.
Before:
After:
I had to change the order of link formatting to make this work: now it normalizes first, encodes second (otherwise it double encodes which messes up the link). I don't think it should change anything in the output.
> Strip tracking params from YouTube links

- assets/chat/js/menus/ChatUserInfoMenu.js
- assets/views/embed.html
Added a subheader to the user info menu when a user is watching an embed on dgg.
The subheader is removed if the user is not watching anything.
> Show what a user is watching in the user info menu

- assets/chat/js/chat.js
tbh may be better to separate this snippet into a `watching-focus.js` or add this into `focus.js` or something, but this pr is just a quick fix to indicate that watching focus is active. if the refactor to separate class is wanted can update to include that as well
#373
> Toggle watching focus btn active on click

- assets/chat/js/messages/ChatUserMessage.js
- assets/chat/js/window.js
> fix: `/me` messages in message history having the colon thingy

- assets/chat/css/style.scss
i have very little experience with javascript so if there's some bad practice/ugly code stuff that needs fixed pls lmk
this should solve #372, sets a MutationObserver to check if `focus` is on the ui element classlist or not. If `focus` is added or removed, sets `watching-focus` state accordingly
> don't apply watching focus if focus active

- assets/chat/css/style.scss
- assets/chat/js/const.js
- assets/views/embed.html
Adds an option to disable the emote animations (the GIF/APNG ones still work, since as far as I'm aware there's no simple way to turn them off) and the flair animations (the Tier V rainbow gradient thing, for example).
https://github.com/destinygg/chat-gui/assets/41237021/8cc1de8e-74a4-4c3b-8ce5-e66f7de16731
> DES-199: add an option to disable emote and flair animations

- assets/chat/js/chat.js
Before this fix it only added perm-less commands, bc the user was getting assigned later in `onME`. I guess it broke when that event got added (or maybe it never worked right in the first place).
Anyway, this change fixes it.
> fix: generate command autocomplete for mods correctly

- assets/chat/js/formatters/MentionedUserFormatter.js
- Adjust the regular expression in the `format` method to correctly match mentions followed by an apostrophe, ensuring that names like "77Y's" are highlighted as expected.
> fix: update regex to include apostrophes in MentionedUserFormatter

- assets/views/embed.html
this PR is for this open issue: https://github.com/destinygg/chat-gui/issues/455
change the enter key to show "send" on virtual keyboards.
iphone virtual keyboard after the change:
> add enterkeyhint property to chat textarea

- assets/chat/css/style.scss
- assets/chat/js/formatters/EmbedUrlFormatter.js
- assets/chat/js/formatters/UrlFormatter.js
- assets/common.scss
Spoilers links will have a dashed pink underline. The issue suggested orange, but I think it will be hard to differentiate from red and yellow. Closes #471
> Add new color for spoilers links

- assets/chat/js/chat.js
- assets/chat/js/messages/ChatEmoteMessage.js
- assets/chat/js/window.js
Adds a user to the `EMOTE` msg type so that the ignore function works properly with them (some people would harsh ignore emotes, but combos would still show up).
> fix: ignore combos

- assets/chat/css/messages/_base.scss
NSFW link styles were mistakenly applied to descendants of `.externallink` when they should be applied to descendants of `.msg-chat`.
> Fix NSFW/NSFL link tagging

- assets/chat/css/chat/_output.scss
Noticed this happening a few months ago, but thought it was only on my end since no one else in chat was complaining (and I was having similar-ish 'ghost frame' issues on Linux before). A week ago someone reported the exact same issue happening on my website as well though (just in a much more exaggerated manner) https://github.com/vyneer/orvods-go/issues/38, so it must be more widespread than I thought initially.
<details>
<summary>Example 1</summary>
Normal speed:
https://github.com/user-attachments/assets/20fd9f12-98ea-442e-8b7e-09853326b148
Slowed down:
https://github.com/user-attachments/assets/0dc5eba6-5959-4e88-84d8-e0b04bfbc7e3
</details>
<details>
<summary>Example 2</summary>
Normal speed:
https://github.com/user-attachments/assets/2a13e761-ce89-43b5-bbd8-3ea259070994
Slowed …
> fix: jumpy chat in firefox

- assets/chat/css/menus/_emote-list.scss
- assets/chat/js/chat.js
- assets/chat/js/menus/ChatEmoteMenu.js
- assets/chat/js/menus/ChatEmoteTooltip.js
- assets/views/embed.html
Removes the favorite emote panel, combines the favorited emote string and the all emote string, removes duplicates, and renders the existing `../img/icon-pin.svg` as a symbol of being favorited/stuck to the top. (probably) Closes #546
> combine emote lists, pin favorited emotes to top

- assets/chat/js/chat.js
- assets/chat/js/event-bar/EventBar.js
- assets/chat/js/focus.js
- assets/chat/js/window.js
This update introduces a hotkey function similar to Discord's. When the chat window is scrolled up, pressing `ESC` will bring the view back to the latest messages.
In DGG, if the chat is not already pinned to the bottom, pressing `ESC` will scroll it down. However, if any menus are open (e.g., emote or settings), `ESC` will first close those menus instead of scrolling. Scrolling will only occur when there are no other actions for `ESC` to perform.
> Added hotkey for ESC key to scroll chat to bottom

- .github/workflows/bump-and-release.yml
A recent PR modified the `prepare` script to use `shx` for Windows interoperability. The `prepare` script is special in that npm always runs it before `npm publish`. This resulted in an error during the execution of our "bump and release" workflow because the workflow doesn't install any Node dependencies.
Simply installing Node dependencies in the workflow fixes the issue. This has the added benefit of catching any last-second formatting or linter errors that slipped through the cracks.
> Fix error when publishing new version

- assets/chat/css/messages/event/_event.scss
> fix: megaphone icon shrinking if there's too much text

- assets/chat/css/chat/event-bar/_event-bar-event.scss
> fix: remove scrolling animation from long usernames in event bar

- assets/chat/css/chat/event-bar/_event-bar-event.scss
fixes a regression introduced by me in https://github.com/destinygg/chat-gui/pull/581 (whoops)
without the fix the donation event looks like this :skull: :
> fix: dont invert the colors of the donation event bar event

- assets/chat/js/chat.js
- assets/chat/js/menus/ChatEmoteMenu.js
- assets/chat/js/menus/ChatEmoteTooltip.js
- assets/chat/js/menus/ChatMenu.js
- assets/chat/js/menus/ChatUserMenu.js
- assets/chat/js/regex.js
Hilariously small useragent regex courtesy of [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent#:~:text=In%20summary%2C%20we%20recommend%20looking%20for%20the%20string%20Mobi%20anywhere%20in%20the%20User%20Agent%20to%20detect%20a%20mobile%20device.).
Otherwise just checking if the chat is in a mobile context before focusing certain input fields.
Issue: #424
> Stop opening virtual keyboard on mobile automatically
