assets/chat/js/menus.js

Fixed chat sorting capitalized names over lowercase

---

assets/chat/js/chat.js
assets/chat/js/mutedtimer.js
package-lock.json
package.json

* Stops the timer and resets the placeholder text when a user is unbanned. An unban triggers an unmute as well.
* Modifies how the timer ticks to prevent it from going into the negatives.

More bug fixes for mute duration timer

---

assets/chat/js/chat.js
assets/chat/js/features.js
assets/chat/js/vote.js
package-lock.json
package.json

Sub-weighted polls are regular polls with pay-to-win DLC. Votes from users with active website subscriptions are more valuable than those without. A vote from a tier 4 sub is worth 16 votes, tier 3 is worth 8, tier 2 is 4, and tier 1 is 2. This kind of poll can be initiated with the `/svote` command. The syntax is otherwise identical to the `/vote` command.
Additionally, this PR polishes some vote-related code in `chat.js` and prints a usage hint when either vote command is improperly used.
```
/vote <question>? <option 1> or <option 2>[ or <option 3>[ or <option 4> ... [ or <option n>]]][ <time>]
```

Introduce sub-weighted polls

---

assets/chat/js/chat.js
assets/chat/js/formatters.js
assets/chat/js/messages.js
assets/views/embed.html
package-lock.json
package.json

Censoring is powered by the `bad-words` module. See [this file](https://github.com/web-mech/badwords/blob/f4d9dd2f982eb3f5449bdb3fe4af674a6f116f33/lib/lang.json) for a complete list of bad words.

Create new setting to censor bad words in chat message

---

assets/chat/css/style.scss

Fix scrollbars showing on Chrome v100

---

assets/chat/js/menus.js

Fixed issue "Custom Highlights"

---

assets/chat/js/chat.js

- Adds multi-user /ignore, will come in handy if a lot of people are telling you how to close Vim all the time
- Adds multi-user /unignore, if you decide to learn how to close Vim again
- Adds /unignoreall, if you want a fresh start
/unignoreall requires a confirmation, so that you don't accidentally clear out your precious ignore list.
https://user-images.githubusercontent.com/41237021/198858470-562e0a1f-8b49-4e31-84cf-ca8b98225ce0.mp4

/ignore and /unignore improvements

---

assets/chat/css/style.scss
assets/chat/js/vote.js

Issue #20
Fixed issue with vote UI not allowing more than 9 options.

Fixed issue with vote UI not allowing more than 9 options.

---

assets/chat/css/style.scss
assets/chat/js/focus.js
assets/chat/js/menus/ChatUserMenu.js
assets/chat/js/messages/ChatUserMessage.js

Highlight by flair.

---

assets/chat/js/chat.js
assets/chat/js/vote.js

Shows vote UI when joining chat after the vote was initiated. #32 
May need more testing, but the from tests I have done it works perfectly.

Historical voting

---

assets/chat/js/chat.js

fix: names not displaying in DM history (#85)

---

assets/chat/css/style.scss
assets/chat/js/chat.js
assets/chat/js/emotes.js
assets/chat/js/menus/ChatEmoteTooltip.js
assets/chat/js/menus/index.js
assets/views/embed.html

Added emote tooltip.
Click emote in chat pops up emote tooltip.
Shows creator if has one.
Click emote in tooltip to put it in the chat input.
https://user-images.githubusercontent.com/13901269/208824046-328ad406-da30-423d-8532-f7f42d1e6211.mp4

Emote tooltip

---

assets/chat/js/chat.js
assets/chat/js/formatters/EmbedUrlFormatter.js

- Add #rumble/blahblah embed formatting
- Add Rumble support to /embed and /postembed

Add Rumble embed support

---

assets/chat/js/chat.js

Was in chat earlier and some users noticed that you can add yourself to your own ignore list and it will (obviously) block out the messages you send - if you accidentally manage to do this it could be somewhat problematic, so maybe it's best to prevent users from doing this.
If this is an intended feature then disregard this pr!

update ignore command to prevent users from adding themselves to their ignore list

---

.env.example
.gitignore
README.md
assets/demo.js
package-lock.json
package.json
webpack.config.js

Configure Webpack dev server to allow connections to prod chat

---

assets/chat/css/style.scss
assets/chat/img/icon-pin.svg
assets/chat/js/chat.js
assets/chat/js/messages/PinnedMessage.js

Adds a button to show the dismissed pinned message again.
https://user-images.githubusercontent.com/41237021/215058676-f80cf42f-12c9-4da9-a54f-d9c5bbb74f5b.mp4

feat: add a "show dismissed pin" button

---

assets/chat/css/style.scss
assets/chat/js/poll.js
assets/views/embed.html

Display user that started poll

---

assets/chat/js/menus/ChatEmoteTooltip.js

fix: make the emote tooltip show up on right click instead

---

assets/chat/css/style.scss
assets/chat/js/poll.js

Fixed poll option css

---

assets/chat/js/scroll.js

I couldn't reproduce the issue, but this _should_ close #132

fix: horizontal scrollbar appearing out of nowhere

---

assets/chat/css/style.scss

now looks slightly less scuffed
https://user-images.githubusercontent.com/41237021/216797213-96af6e6a-14c1-4e71-9c43-c6549e34bc91.mp4

Pinned message design tweaks

---

assets/chat/js/poll.js

Floor chat message end poll percentage.

Floor chat message end poll percentage.

---

package-lock.json
package.json

We use the browser's native WS capabilities.

Remove unused ws dependency

---

package-lock.json
package.json
webpack.config.js

- Use asset/resource module over file-loader
- Remove unused file-loader dep

Fix issue with icons not loading

---

assets/chat/css/style.scss
assets/chat/js/chat.js
assets/chat/js/poll.js
assets/common.scss
assets/views/embed.html

https://user-images.githubusercontent.com/13901269/221339372-87f6cc02-a075-41ef-b914-858d6a41de35.mp4

Updated poll ui

---

assets/chat/js/chat.js
assets/chat/js/source.js

fix: long disconnects on 1001 close code

---

assets/chat/js/chat.js
assets/chat/js/emotes.js
assets/chat/js/menus/ChatEmoteMenu.js
assets/chat/js/menus/ChatEmoteTooltip.js

Fix sub only emote combos. And refactor emote service to use a map.

Fix sub only emote combos. And refactor emote service to use a map.

---

assets/chat/js/chat.js
assets/chat/js/features.js
assets/chat/js/poll.js

Required chat PR of same name.

Poll permissions fix

---

assets/chat/js/chat.js
webpack.config.js

If the cookie request header does not already exist, an error is thrown for attempting to call .replace on null.
Additionally, the bakeCookies function assumed that the sid would already exist in the cookie, which is not necessarily true.

Bug fixes with setting cookie values.

---

assets/chat/js/chat.js
assets/demo.js

Needs website and chat PR of same name.

Only get user info if logged in

---

assets/chat/js/chat.js

Linked chat-gui PR [#150](https://github.com/destinygg/website-private/pull/150)

Remove stalk/mention cooldown

---

.github/workflows/test.yml

Adds a test.yml workflow action which runs npm run test on PR (jest)
Green PR: https://github.com/Riott/chat-gui/pull/5
Red PR: https://github.com/Riott/chat-gui/pull/4
resolves #234

Add unit test PR action

---

assets/chat/js/chat.js

Linked website pr [#153](https://github.com/destinygg/website-private/pull/153)

Show error in private message for non existing user.

---

.eslintrc.js
assets/chat/js/chat.js
assets/chat/js/messages/ChatEventMessage.js
assets/chat/js/messages/ChatMessage.js
assets/chat/js/messages/ChatUIMessage.js
assets/chat/js/messages/ChatUserMessage.js
assets/chat/js/messages/index.js
assets/chat/js/window.js

Note: doesn't work with the setting to censor bad words.

Update all messages when chat settings or auth state change

---

assets/chat/js/chat.js

fix: autocomplete being lowercase

---

assets/chat/js/messages/subscriptions/ChatGiftedSubscriptionMessage.js

Forgot to change the gift recipient username to `displayName` in https://github.com/destinygg/chat-gui/pull/339
Before:
After:

fix: gift recipients being lowercase

---

assets/chat/js/formatters/UrlFormatter.js

Fix bad YouTube links breaking chat

---

assets/chat/css/style.scss

fix: onstreamchat broadcast msgs being ugly

---

assets/chat/js/chat.js
assets/chat/js/roles.js
assets/chat/js/user.js

https://github.com/destinygg/website-private/pull/305

Update host permissions

---

assets/chat/js/hashlinkconverter.js
assets/chat/js/hashlinkconverter.test.js

I made the /embed command work with "https://www.youtube.com/embed/*" links, and fixed what I think is repeated code.

Optimize & Add youtube embed links support

---

assets/chat/js/hashlinkconverter.js
assets/chat/js/hashlinkconverter.test.js

- Any Youtube link with `t` parameter can be embeded with timestamp.
Closes #470

Add support for timestamped Youtube links

---

assets/chat/js/autocomplete.js

Fixes a couple of things:
- suggestions getting cut off sometimes
- helper not resetting on new suggestions
I also made the code a bit more readable (imo).
Before:
https://github.com/user-attachments/assets/f1a53830-9873-484c-834e-aeb5e88871fb
After:
https://github.com/user-attachments/assets/053a3d46-0fb4-4880-bdc5-23e83f30103b

fix some autocomplete helper quirks

---

assets/chat/js/menus/ChatUserMenu.js

Addresses the root cause of https://github.com/destinygg/chat-gui/pull/496

fix: user list elements not getting removed sometimes

---

assets/chat/css/chat/_autocomplete.scss
assets/chat/css/components/_form-control.scss
assets/chat/css/style.scss

update built in module function calls & imports for sass 1.80

---

assets/chat/css/chat/event-bar/_event-bar-event.scss
assets/chat/js/event-bar/EventBar.js

Dismiss selected event by clicking it again

---

assets/chat/js/chat.js
assets/chat/js/messages/ChatEmoteMessage.js
assets/chat/js/messages/MessageBuilder.js
assets/chat/js/window.js

https://github.com/destinygg/chat-private/pull/63

History changes and fixes

---

assets/chat/js/chat.js

Temporary mute message now has links to the subscription and donate pages.

Update chat.js temporary mute message

---

assets/chat/js/menus/ChatUserInfoMenu.js

fix shortlinks being broken in user info menu

---

assets/chat/js/chat.js
assets/chat/js/messages/ChatBroadcastMessage.js
assets/chat/js/messages/MessageBuilder.js

fix: add uuids to broadcasts

---

assets/chat/js/autocomplete.js

This pull request implements the feature suggestion from #668

Implemented #668 (autocomplete recent mentions)

---

assets/chat/js/menus/ChatUserInfoMenu.js

At request of jojoP this makes the Watching: section in the right click user info menu a clickable link to what the person is watching.

Watching info in right click info menu is now a clickable link
